---
# Copyright (c) Tongdun Corporation. All rights reserved.
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s %(filename)s:%(lineno)d %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 1048576000 # 1000MB
    backupCount: 10
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: errors.log
    backupCount: 10
    encoding: utf8

loggers:
  "app":
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]
